
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: Adriano S. Fonseca
email: new.adriano.fonseca@gmail.com
description: My name is Adriano da Silva Fonseca > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://adriano-fonseca.github.io" # the base hostname & protocol for your site

twitter_username: adriano_fonseca
github_username: adriano-fonseca
linkedin_username: adriano-s-fonseca-18b975b2

# Where are tags and categories displayed
tag_page: '/blog/tag/'
category_page: '/blog/category/'


# Base URL of site. It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
# baseurl: "/" # the subpath of your site
url: "https://adriano-fonseca.github.io/" # the base hostname & protocol for your site
baseurl: ""
cover: "/assets/cover.png"
logo: "/assets/logo.png"

# Site configurations
gems: 
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."
